In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

# Define the path to the Dataset folder
folder_path = '/content/drive/MyDrive/Sanskrit_LLM/Dataset'

# List contents of the folder to identify the file
print(f"Contents of {folder_path}:")
if os.path.exists(folder_path):
    for item in os.listdir(folder_path):
        print(item)
else:
    print(f"Folder not found: {folder_path}")

Contents of /content/drive/MyDrive/Sanskrit_LLM/Dataset:
disease_ontology.json
Raw_texts
Book_Names.json
NATIONAL AYURVEDA MORBIDITY CODES.xlsx
Sample_KG_Data
charaka_dataset.json
charaka_tree_dataset.json
charaka_tree_cleaned.json
Top Diseases.gsheet
DATASET.gsheet

In [ ]:
# Install gspread if not already installed
!pip install gspread oauth2client

import gspread
from google.colab import auth
import pandas as pd
import google.auth # Import google.auth

# Authenticate Google Colab to access Google Drive and Sheets
# This will prompt you to authorize access in your browser.
auth.authenticate_user()

# Get default credentials and authorize gspread with them
creds, _ = google.auth.default()
gc = gspread.authorize(creds)

try:
    # Open the spreadsheet by its name. Assuming the actual Google Sheet is also named 'DATASET'.
    # If the sheet has a different name, you will need to update this.
    spreadsheet_name = 'DATASET'
    worksheet = gc.open(spreadsheet_name).worksheet("IAST_1000")

    # Get all values from the worksheet as a list of lists
    data = worksheet.get_all_values()

    # Convert to pandas DataFrame
    # The first row is assumed to be the header
    df_gsheet = pd.DataFrame(data[1:], columns=data[0])

    print(f"Successfully read Google Sheet '{spreadsheet_name}' into a DataFrame.")
    display(df_gsheet.head())

except gspread.exceptions.SpreadsheetNotFound:
    print(f"Error: Google Sheet '{spreadsheet_name}' not found. Please ensure the name is correct and you have access to it.")
except Exception as e:
    print(f"An error occurred while reading the Google Sheet: {e}")

Requirement already satisfied: gspread in /usr/local/lib/python3.12/dist-packages (6.2.1)
Requirement already satisfied: oauth2client in /usr/local/lib/python3.12/dist-packages (4.1.3)
Requirement already satisfied: google-auth>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from gspread) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gspread) (1.3.1)
Requirement already satisfied: httplib2>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.31.2)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.6.3)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (0.4.2)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (4.9.1)
Requirement already satisfied: six>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from oauth2client) (1.17.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.4.1->gspread) (2.0.0)
Requirement already satisfied: pyparsing<4,>=3.1 in /usr/local/lib/python3.12/dist-packages (from httplib2>=0.9.1->oauth2client) (3.3.2)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.3.1)
Requirement already satisfied: requests>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.4.1->gspread) (2026.2.25)
Successfully read Google Sheet 'DATASET' into a DataFrame.

,IAST_term,English_meaning,input_text,target_text,ByT5_Output,Ind_ByT5_Combined_Hindi_OP,Ind_ByT5_Sanskrit_OP,NLLB_Devanagari_OP,NLLB_IAST_OP,Indic_Sanskrit_OP,Sarvam_Devanagari_OP,Sarvam_IAST_OP,Qwen_IAST_OP,Qwen_Devanagari_OP,Nalanda_Devanagari_OP,Srvm_op_test
0,hikkā,hiccup,symptom: hiccup,hikkā,,हिचकी,,आयुर्वेदिकं लक्षणवर्णनं - हिकुकम् ।,āyurvedikaṃ lakṣaṇavarṇanaṃ - hikukam .,हिचकः ।,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,kṣudra-kṣumba,क्षुद्र-क्षुम्ब,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",हिक्का
1,śvāsa,breathlessness/difficult breathing,symptom: breathlessness/difficult breathing,śvāsa,,सांस फूलना / सांस लेने में कठिनाई,symptom / Sanskrit Hindi,आयुर्वेदिकं लक्षणवर्णनं- श्वासं न श्वासः/ श्वा...,āyurvedikaṃ lakṣaṇavarṇanaṃ- śvāsaṃ na śvāsaḥ/...,श्वासोच्छ्वासस्य अभावः / कष्टप्रदः श्वासोच्छ्वासः,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,kṣvabhāva,क्ष्वभाव,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",श्वसनकष्टम्/कठिनश्वासः
2,cakṣurādīnāmupaghāta,impairment of eye,symptom: impairment of sense organs viz. eye,cakṣurādīnāmupaghāta,,आँखों की हानि,translation,आयुर्वेदिकं लक्षणवर्णनं- नेत्रदोषः ।,āyurvedikaṃ lakṣaṇavarṇanaṃ- netradoṣaḥ .,नेत्रदोषः ।,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,śūdrāna,शूद्रान,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",नेत्रक्षतिः
3,pīnasa,"cold, catarrh","symptom: cold, catarrh",pīnasa,,शीत पित्त,translation,"आयुर्वेदिकं लक्षणवर्णनं - सर्दी, कैटार्ह","āyurvedikaṃ lakṣaṇavarṇanaṃ - sardī, kaiṭārha",शीतकालः - शीतकालः - शीतकालः - शीतकालः - शीतकाल...,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,śirāśira,शिराशिर,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...","शीत, श्लेष्म"
4,ardita,facial paralysis,symptom: facial paralysis,ardita,,चेहरे का पक्षाघात,symptom,आयुर्वेदिकं लक्षणवर्णनं- अनुहारस्य पक्षाघातः ।,āyurvedikaṃ lakṣaṇavarṇanaṃ- anuhārasya pakṣāg...,मुखस्य पक्षाघातः ।,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,ardita,अर्दित,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",मुखपक्षाघातः

In [ ]:
!pip install -U transformers

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Collecting transformers
  Downloading transformers-5.5.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.8.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.3)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.25.2)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.4.2)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->transformers) (0.1.2)
Downloading transformers-5.5.0-py3-none-any.whl (10.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 77.6 MB/s eta 0:00:00
Installing collected packages: transformers
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
Successfully installed transformers-5.5.0

In [ ]:
# Load model directly
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer = AutoTokenizer.from_pretrained("chronbmm/sanskrit5-multitask")
model = AutoModelForSeq2SeqLM.from_pretrained("chronbmm/sanskrit5-multitask")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/866 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer_config.json: 0.00B [00:00, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/2.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/252 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie shared.weight to lm_head.weight, but both are present in the checkpoints with different values, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning.

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

In [ ]:
import torch
from tqdm import tqdm


device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

def translate_batch(text_list):
    inputs = [
        f"translate English to Sanskrit (IAST): {str(t)}"
        for t in text_list
    ]

    tokenized = tokenizer(
        inputs,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=128
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **tokenized,
            max_length=80,
            num_beams=4,
            do_sample=False,
            early_stopping=True
        )

    decoded = tokenizer.batch_decode(outputs, skip_special_tokens=True)
    decoded = [d.strip() for d in decoded]

    return decoded

In [ ]:
batch_size = 16   # reduce to 8 if OOM

results = []

texts = df_gsheet["English_meaning"].fillna("").astype(str).tolist()

for i in tqdm(range(0, len(texts), batch_size)):
    batch = texts[i:i+batch_size]
    translated = translate_batch(batch)
    results.extend(translated)


# -----------------------------
# Store output column
# -----------------------------
df_gsheet["Sanskrit5_Output"] = results


# -----------------------------
# Upload back to Google Sheet
# -----------------------------
spreadsheet = gc.open("DATASET")
worksheet = spreadsheet.worksheet("IAST_1000")

worksheet.clear()

data_to_upload = [df_gsheet.columns.values.tolist()] + df_gsheet.values.tolist()

worksheet.update(data_to_upload)

df_gsheet.head()

100%|██████████| 64/64 [14:09<00:00, 13.27s/it]

,IAST_term,English_meaning,input_text,target_text,ByT5_Output,Ind_ByT5_Combined_Hindi_OP,Ind_ByT5_Sanskrit_OP,NLLB_Devanagari_OP,NLLB_IAST_OP,Indic_Sanskrit_OP,Sarvam_Devanagari_OP,Sarvam_IAST_OP,Qwen_IAST_OP,Qwen_Devanagari_OP,Nalanda_Devanagari_OP,Srvm_op_test,Sanskrit5_Output
0,hikkā,hiccup,symptom: hiccup,hikkā,,हिचकी,,आयुर्वेदिकं लक्षणवर्णनं - हिकुकम् ।,āyurvedikaṃ lakṣaṇavarṇanaṃ - hikukam .,हिचकः ।,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,kṣudra-kṣumba,क्षुद्र-क्षुम्ब,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",हिक्का,hiccup_hiccup_SNM
1,śvāsa,breathlessness/difficult breathing,symptom: breathlessness/difficult breathing,śvāsa,,सांस फूलना / सांस लेने में कठिनाई,symptom / Sanskrit Hindi,आयुर्वेदिकं लक्षणवर्णनं- श्वासं न श्वासः/ श्वा...,āyurvedikaṃ lakṣaṇavarṇanaṃ- śvāsaṃ na śvāsaḥ/...,श्वासोच्छ्वासस्य अभावः / कष्टप्रदः श्वासोच्छ्वासः,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,kṣvabhāva,क्ष्वभाव,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",श्वसनकष्टम्/कठिनश्वासः,breathlessness_breathlessness_U __different_U ...
2,cakṣurādīnāmupaghāta,impairment of eye,symptom: impairment of sense organs viz. eye,cakṣurādīnāmupaghāta,,आँखों की हानि,translation,आयुर्वेदिकं लक्षणवर्णनं- नेत्रदोषः ।,āyurvedikaṃ lakṣaṇavarṇanaṃ- netradoṣaḥ .,नेत्रदोषः ।,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,śūdrāna,शूद्रान,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",नेत्रक्षतिः,impairment_ob_U eye_eye_U
3,pīnasa,"cold, catarrh","symptom: cold, catarrh",pīnasa,,शीत पित्त,translation,"आयुर्वेदिकं लक्षणवर्णनं - सर्दी, कैटार्ह","āyurvedikaṃ lakṣaṇavarṇanaṃ - sardī, kaiṭārha",शीतकालः - शीतकालः - शीतकालः - शीतकालः - शीतकाल...,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,śirāśira,शिराशिर,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...","शीत, श्लेष्म",cold_cold_U
4,ardita,facial paralysis,symptom: facial paralysis,ardita,,चेहरे का पक्षाघात,symptom,आयुर्वेदिकं लक्षणवर्णनं- अनुहारस्य पक्षाघातः ।,āyurvedikaṃ lakṣaṇavarṇanaṃ- anuhārasya pakṣāg...,मुखस्य पक्षाघातः ।,संस्कृतभाषायाः संस्कृतसंस्कृतसंस्कृतिं संस्कृत...,saṃskṛtabhāṣāyāḥ saṃskṛtasaṃskṛtasaṃskṛtiṃ saṃ...,ardita,अर्दित,"स्तत्स्: {ऽतोकेन्स्चोन्सुमेद्ऽ: ५१२, ऽतोकेन्स्...",मुखपक्षाघातः,facial_paralysis_